import { TRendererComponents } from 'localTypes/dynamicRender'
import {
  DefaultDiv,
  AntdText,
  AntdCard,
  AntdFlex,
  AntdRow,
  AntdCol,
  AntdTabs,
  AntdButton,
  PartsOfUrl,
  MultiQuery,
  ParsedText,
  ProjectInfoCard,
  MarketplaceCard,
  ContentCard,
  Spacer,
  StatusText,
  SidebarProvider,
  EnrichedTable,
  PodTerminal,
  NodeTerminal,
  PodLogs,
  YamlEditorSingleton,
} from './molecules'
import { TDynamicComponentsAppTypeMap } from './types'

export const DynamicComponents: TRendererComponents<TDynamicComponentsAppTypeMap> = {
  DefaultDiv,
  antdText: AntdText,
  antdCard: AntdCard,
  antdFlex: AntdFlex,
  antdRow: AntdRow,
  antdCol: AntdCol,
  antdTabs: AntdTabs,
  antdButton: AntdButton,
  partsOfUrl: PartsOfUrl,
  multiQuery: MultiQuery,
  parsedText: ParsedText,
  ProjectInfoCard,
  MarketplaceCard,
  ContentCard,
  Spacer,
  StatusText,
  SidebarProvider,
  EnrichedTable,
  PodTerminal,
  NodeTerminal,
  PodLogs,
  YamlEditorSingleton,
}
