import { TRendererComponents } from 'localTypes/dynamicRender'
import {
  DefaultDiv,
  AntdText,
  AntdCard,
  AntdFlex,
  AntdRow,
  AntdCol,
  AntdTabs,
  AntdButton,
  PartsOfUrl,
  MultiQuery,
  ParsedText,
  ProjectInfoCard,
  MarketplaceCard,
  ContentCard,
  Spacer,
  StatusText,
  SidebarProvider,
  EnrichedTable,
  PodTerminal,
  NodeTerminal,
  PodLogs,
  VMVNC,
  YamlEditorSingleton,
  AntdLink,
  VisibilityContainer,
  ArrayOfObjectsToKeyValues,
  ItemCounter,
  Labels,
  LabelsToSearchParams,
  KeyCounter,
  Taints,
  Tolerations,
  Annotations,
  ConverterBytes,
  SecretBase64Plain,
  ResourceBadge,
  Events,
} from './molecules'
import { TDynamicComponentsAppTypeMap } from './types'

export const DynamicComponents: TRendererComponents<TDynamicComponentsAppTypeMap> = {
  DefaultDiv,
  antdText: AntdText,
  antdLink: AntdLink,
  antdCard: AntdCard,
  antdFlex: AntdFlex,
  antdRow: AntdRow,
  antdCol: AntdCol,
  antdTabs: AntdTabs,
  antdButton: AntdButton,
  partsOfUrl: PartsOfUrl,
  multiQuery: MultiQuery,
  parsedText: ParsedText,
  ProjectInfoCard,
  MarketplaceCard,
  ContentCard,
  Spacer,
  StatusText,
  SidebarProvider,
  EnrichedTable,
  PodTerminal,
  NodeTerminal,
  PodLogs,
  VMVNC,
  YamlEditorSingleton,
  VisibilityContainer,
  ArrayOfObjectsToKeyValues,
  ItemCounter,
  Labels,
  LabelsToSearchParams,
  KeyCounter,
  Taints,
  Tolerations,
  Annotations,
  ConverterBytes,
  SecretBase64Plain,
  ResourceBadge,
  Events,
}
